---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: Unterstützung durch die BlueXP Synchronisierung und Kopie erhalten Sie und weitere Informationen über verschiedene Ressourcen wie Foren, Chat-Services und Videos. 
---
= Technische FAQ zum Kopieren und Synchronisieren von BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur eine schnelle Antwort auf eine Frage suchen.



== Erste Schritte

Die folgenden Fragen beziehen sich auf die ersten Schritte mit der BlueXP Kopier- und Synchronisierungsfunktion.



=== Wie funktioniert BlueXP Kopier- und Synchronisierungsfunktion?

Die Kopier- und Synchronisierungsfunktion von BlueXP verwendet die NetApp Daten-Broker-Software, um Daten von einer Quelle auf ein Ziel zu synchronisieren (dies wird als _Sync Relationship_ bezeichnet).

Eine Gruppe von Datenmaklern steuert die Synchronisierungsbeziehungen zwischen Ihren Quellen und Zielen. Nach Einrichtung einer Synchronisierungsbeziehung analysiert BlueXP Ihr Quellsystem und unterteilt es in mehrere Replizierungs-Streams, um es auf Ihre ausgewählten Zieldaten zu übertragen.

Nach der ersten Kopie synchronisiert der Service alle geänderten Daten auf der Grundlage des von Ihnen festgelegten Zeitplans.



=== Wie funktioniert die 14-tägige kostenlose Testversion?

Die kostenlose 14-Tage-Testversion beginnt, wenn Sie sich für den BlueXP Kopier- und Synchronisierungsservice anmelden. Sie unterliegen keinen NetApp Gebühren für BlueXP Kopier- und Synchronisierungsbeziehungen, die Sie 14 Tage lang erstellen. Alle Gebühren für die Ressourcen aller von Ihnen implementierten Daten-Broker sind jedoch nach wie vor gültig.



=== Was kostet BlueXP Kopier- und Synchronisierungskosten?

Für die Nutzung der BlueXP Kopier- und Synchronisierungsfunktion gibt es zwei Arten von Kosten: Servicegebühren und Ressourcengebühren.

*Servicegebühren*

Bei einem nutzungsbasierten Preismodell fallen die Gebühren für den Kopier- und Synchronisierungsservice von BlueXP basierend auf der Anzahl der erstellten Synchronisierungsbeziehungen stündlich an.

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["Pay-as-you-go-Preise in AWS anzeigen"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Jährliche Preise in AWS anzeigen"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Preise in Azure anzeigen"^]


BlueXP Kopier- und Synchronisierungslizenzen sind auch über Ihren NetApp Ansprechpartner erhältlich. Jede Lizenz ermöglicht 20 Synchronisierungsbeziehungen für 12 Monate.

link:concept-licensing.html["Weitere Informationen zu Lizenzen"].


NOTE: BlueXP  Kopier- und Synchronisierungsbeziehungen sind für Azure NetApp Files kostenlos.

*Ressourcengebühren*

Die Ressourcenkosten beziehen sich auf die Computing- und Storage-Kosten für die Ausführung des Data Brokers in der Cloud.



=== Wie werden die Kosten für den Kopiervorgang und die Synchronisierung von BlueXP berechnet und wie verwalte ich mein Abonnement?

Es gibt zwei Möglichkeiten, für Synchronisierungsbeziehungen zu bezahlen, nachdem die 14-tägige kostenlose Testversion abgelaufen ist. Die erste Möglichkeit besteht darin, AWS oder Azure zu abonnieren, sodass Sie nutzungsbasiert oder jährlich zahlen können. Die zweite Option besteht darin, Lizenzen direkt von NetApp zu erwerben. In jedem Fall wird Ihr Abonnement über Ihren Provider Marketplace gemanagt und *nicht* über die BlueXP Kopier- und Synchronisierungsschnittstelle.



=== Kann ich BlueXP außerhalb der Cloud kopieren und synchronisieren?

Ja, BlueXP Kopier- und Synchronisierungsfunktion ist in einer Architektur außerhalb der Cloud möglich. Quelle und Ziel können On-Premises residieren – ebenso wie die Software für Datenmanager.

Beachten Sie die folgenden zentralen Punkte zur Nutzung von BlueXP Kopier- und Synchronisierungsfunktion außerhalb der Cloud:

* Eine Datenbrokergruppe benötigt eine Internetverbindung, um mit dem BlueXP Kopier- und Synchronisierungsservice zu kommunizieren.
* Wenn Sie keine Lizenz direkt von NetApp erwerben, benötigen Sie ein AWS- oder Azure-Konto für die Abrechnung des PAYGO BlueXP Kopier- und Synchronisierungsservice.




=== Wie erhalte ich Zugriff auf die BlueXP Kopier- und Synchronisierungsfunktion?

BlueXP Kopier- und Synchronisierungsfunktion ist auf der BlueXP Website auf der Registerkarte *Sync* verfügbar.



=== Was ist eine Data Broker-Gruppe?

Jeder Daten-Broker gehört zu einer Data Broker-Gruppe. Das Zusammenführen von Datenmaklern trägt zu einer verbesserten Performance von Synchronisierungsbeziehungen bei.



== Unterstützte Quellen und Ziele

Die folgenden Fragen beziehen sich auf die Quelle und die Ziele, die in einer Synchronisierungsbeziehung unterstützt werden.



=== Welche Quellen und Ziele unterstützt BlueXP beim Kopieren und Synchronisieren?

BlueXP Kopier- und Synchronisierungsfunktion unterstützt viele unterschiedliche Arten von Synchronisierungsbeziehungen. link:reference-supported-relationships.html["Die gesamte Liste anzeigen"].



=== Welche Versionen von NFS und SMB unterstützt BlueXP beim Kopieren und Synchronisieren?

Die Kopier- und Synchronisierungsfunktion von BlueXP unterstützt NFS-Version 3 und höher sowie SMB-Version 1 und höher.

link:reference-requirements.html["Erfahren Sie mehr über Synchronisierungsanforderungen"].



=== Wenn Amazon S3 das Ziel ist, können die Daten auf eine bestimmte S3-Storage-Klasse gestaffelt werden?

Ja, Sie können eine bestimmte S3-Storage-Klasse auswählen, wenn AWS S3 das Ziel ist:

* Standard (dies ist die Standardklasse)
* Intelligent-Tiering
* Standardzugriff
* Ein einmaliger Zugriff
* Glacier Deep Archive
* Flexibles Abrufen Von Glacier
* Glacier Instant Retrieval




=== Was ist mit Storage Tiers für Azure Blob Storage?

Sie können eine bestimmte Azure Blob Storage Tier auswählen, wenn ein Blob Container das Ziel ist:

* Hot-Storage
* Kühl lagern




=== Unterstützen Sie Google Cloud Storage Tiers?

Ja, Sie können eine bestimmte Storage-Klasse auswählen, wenn ein Google Cloud Storage-Bucket Ziel ist:

* Standard
* Nearline
* Coldline
* Archivierung




== Netzwerkbetrieb

Die folgenden Fragen beziehen sich auf Netzwerkanforderungen für die BlueXP Kopier- und Synchronisierungsfunktion.



=== Was sind die Netzwerkanforderungen an die BlueXP Kopier- und Synchronisierungsfunktion?

Für die BlueXP Kopier- und Synchronisierungsumgebung muss eine Daten-Broker-Gruppe über das ausgewählte Protokoll oder die Objekt-Storage-API (Amazon S3, Azure Blob, IBM Cloud Objekt-Storage) mit der Quelle und dem Ziel verbunden sein.

Darüber hinaus benötigt eine Datenbrokergruppe eine Outbound-Internetverbindung über Port 443, damit sie mit dem BlueXP Kopier- und Synchronisierungsservice kommunizieren und einige andere Services und Repositorys kontaktieren kann.

Weitere Informationen link:reference-networking.html["Netzwerkanforderungen prüfen"].



=== Kann ich einen Proxy-Server mit dem Daten-Broker verwenden?

Ja.

Die Kopier- und Synchronisierungsfunktion von BlueXP unterstützt Proxyserver mit oder ohne grundlegende Authentifizierung. Wenn Sie einen Proxyserver angeben, wenn Sie einen Datenmanager bereitstellen, wird der gesamte HTTP- und HTTPS-Datenverkehr vom Datenmanager über den Proxy weitergeleitet. Beachten Sie, dass nicht-HTTP-Datenverkehr wie NFS oder SMB nicht über einen Proxy-Server weitergeleitet werden können.

Die einzige Einschränkung für Proxy-Server besteht in der Nutzung der Verschlüsselung von Daten während der Übertragung mit einer NFS- oder Azure NetApp Files-Synchronisierungsbeziehung. Die verschlüsselten Daten werden über HTTPS gesendet und sind nicht über einen Proxy-Server routingfähig.



== Datensynchronisierung

Die folgenden Fragen beziehen sich auf die Funktionsweise der Datensynchronisierung.



=== Wie oft erfolgt die Synchronisierung?

Der Standardzeitplan ist für die tägliche Synchronisierung festgelegt. Nach der ersten Synchronisierung können Sie:

* Ändern Sie den Synchronisierungszeitplan auf die gewünschte Anzahl von Tagen, Stunden oder Minuten
* Deaktivieren Sie den Synchronisierungszeitplan
* Synchronisierungszeitplan löschen (keine Daten verloren; nur die Synchronisierungsbeziehung wird entfernt)




=== Wie ist der Mindestsynchronisierungszeitplan?

Sie können eine Beziehung planen, um Daten bis zu alle 1 Minute zu synchronisieren.



=== Wird der Daten-Broker erneut versucht, wenn eine Datei nicht synchronisiert wird? Oder wird das Zeitlimit überschritten?

Eine Datenmaklergruppe hat kein Timeout, wenn eine einzelne Datei nicht übertragen werden kann. Stattdessen versucht die Gruppe des Datenmakers 3 Mal erneut, bevor die Datei übersprungen wird. Der Wiederholungswert kann in den Einstellungen für eine Synchronisierungsbeziehung konfiguriert werden.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["Hier erfahren Sie, wie Sie die Einstellungen für eine Synchronisierungsbeziehung ändern"].



=== Was ist, wenn ich einen sehr großen Datensatz habe?

Wenn ein einzelnes Verzeichnis 600.000 Dateien oder mehr enthält,link:task-get-help.html["Kontakt"] damit wir Ihnen bei der Konfiguration der Datenbrokergruppe zur Handhabung der Nutzlast helfen können.  Möglicherweise müssen wir der Datenbrokergruppe zusätzlichen Speicher hinzufügen.

Beachten Sie, dass die Gesamtanzahl der Dateien im Bereitstellungspunkt nicht begrenzt ist. Der zusätzliche Speicher ist für große Verzeichnisse mit 600,000 Dateien oder mehr erforderlich, unabhängig von deren Ebene in der Hierarchie (Top-Verzeichnis oder Unterverzeichnis).



== Sicherheit

Die folgenden Fragen zur Sicherheit.



=== Ist das Kopieren und Synchronisieren von BlueXP sicher?

Ja. Die gesamte Networking-Konnektivität des BlueXP Kopier- und Synchronisierungsservice wird auf Basis von ausgeführt https://aws.amazon.com/sqs/["Amazon Simple Queue Service (SQS)"^].

Die gesamte Kommunikation zwischen der Daten-Broker-Gruppe und Amazon S3, Azure Blob, Google Cloud Storage und IBM Cloud Object Storage erfolgt über das HTTPS-Protokoll.

Bei Verwendung von BlueXP Kopier- und Synchronisierungsfunktion mit On-Premises-Systemen (Quelle oder Ziel) sind hier einige empfohlene Konnektivitätsoptionen zu finden:

* Eine AWS Direct Connect-, Azure ExpressRoute- oder Google Cloud Interconnect-Verbindung, die nicht über das Internet geroutet wird (und nur mit den von Ihnen angegebenen Cloud-Netzwerken kommunizieren kann)
* Eine VPN-Verbindung zwischen Ihrem lokalen Gateway-Gerät und Ihren Cloud-Netzwerken
* Für eine besonders sichere Datenübertragung mit S3-Buckets, Azure Blob Storage oder Google Cloud Storage kann ein Amazon Private S3 Endpoint, Azure Virtual Network Service-Endpunkte oder Private Google Access eingerichtet werden.


Bei jeder dieser Methoden wird eine sichere Verbindung zwischen Ihren lokalen NAS-Servern und einer BlueXP Datenbrokergruppe für die Kopie und Synchronisierung aufgebaut.



=== Werden die Daten durch die BlueXP Kopier- und Synchronisierungsfunktion verschlüsselt?

* Die BlueXP Kopier- und Synchronisierungsfunktion unterstützt die Verschlüsselung von aktiven Daten zwischen Quell- und Ziel-NFS-Servern. link:task-nfs-encryption.html["Weitere Informationen ."].
* Bei SMB unterstützt das Kopieren und Synchronisieren von BlueXP die serverseitigen verschlüsselten SMB 3.0- und 3.11-Daten. Durch das Kopieren und Synchronisieren von BlueXP werden die verschlüsselten Daten von der Quelle zum Ziel kopiert, wo die Daten verschlüsselt bleiben.
+
Die Kopier- und Synchronisierungsfunktion von BlueXP kann SMB-Daten nicht selbst verschlüsseln.

* Wenn ein Amazon S3-Bucket in einer Synchronisierungsbeziehung das Ziel ist, hat der Kunde die Wahl, ob die Datenverschlüsselung mittels AWS KMS-Verschlüsselung oder AES-256-Verschlüsselung aktiviert werden soll.
* Wenn ein Google Storage-Bucket das Ziel in einer Synchronisierungsbeziehung ist, können Sie wählen, ob Sie den standardmäßigen, von Google gemanagten Verschlüsselungsschlüssel oder Ihren eigenen KMS-Schlüssel verwenden möchten.




== Berechtigungen

Die folgenden Fragen beziehen sich auf Datenberechtigungen.



=== Werden SMB-Datenberechtigungen mit dem Zielspeicherort synchronisiert?

Sie können die BlueXP Kopie und Synchronisierung einrichten, um Zugriffssteuerungslisten (Access Control Lists, ACLs) zwischen einer Quell-SMB-Freigabe und einer Ziel-SMB-Freigabe sowie von einer Quell-SMB-Freigabe bis hin zu Objekt-Storage (außer ONTAP S3) beizubehalten.


NOTE: Die BlueXP Kopier- und Synchronisierungsfunktion unterstützt nicht das Kopieren von ACLs vom Objekt-Storage auf SMB-Freigaben.

link:task-copying-acls.html["Lesen Sie, wie Sie ACLs zwischen SMB-Freigaben kopieren"].



=== Werden NFS-Datenberechtigungen mit dem Zielspeicherort synchronisiert?

BlueXP kopiert und synchronisiert automatisch NFS-Berechtigungen zwischen NFS-Servern wie folgt:

* NFS-Version 3: BlueXP kopiert und synchronisiert die Berechtigungen und den Eigentümer der Benutzergruppe.
* NFS-Version 4: BlueXP kopiert und synchronisiert die ACLs.




== Objekt-Storage-Metadaten



=== Welche Arten von synchronen Beziehungen bewahren die Objekt-Storage-Metadaten?

BlueXP Kopier- und Synchronisierungskopien von Objekt-Storage-Metadaten aus der Quelle für die folgenden Arten von Synchronisierungsbeziehungen zum Ziel:

* Amazon S3 -> Amazon S3 ^1^
* Amazon S3 -> StorageGRID
* StorageGRID -> Amazon S3
* StorageGRID -> StorageGRID
* StorageGRID -> Google Cloud Storage
* Google Cloud Storage -> StorageGRID ^1^
* Google Cloud Storage -> IBM Cloud Object Storage ^1^
* Google Cloud Storage -> Amazon S3 ^1^
* Amazon S3 -> Google Cloud Storage
* IBM Cloud Object Storage -> Google Cloud Storage
* StorageGRID -> IBM Cloud Object Storage
* IBM Cloud Object Storage -> StorageGRID
* IBM Cloud Object Storage -> IBM Cloud Object Storage


^1^ für diese Synchronisierungsbeziehungen müssen Sie es durchführen link:task-creating-relationships.html["Aktivieren Sie die Einstellung Kopieren für Objekte, wenn Sie die Synchronisierungsbeziehung erstellen"].



=== Welche Arten von Metadaten werden während der Synchronisierung repliziert, wobei NFS oder SMB die Quelle sind?

Metadaten wie Benutzer-ID, Änderungszeit, Zugriffszeit und GID werden standardmäßig repliziert. Benutzer können ACL von CIFS replizieren, indem sie sie bei der Erstellung einer Synchronisierungsbeziehung als erforderlich markieren.



== Leistung

Die folgenden Fragen beziehen sich auf die Performance der BlueXP Kopier- und Synchronisierungsvorgänge.



=== Was stellt die Fortschrittsanzeige für eine Synchronisierungsbeziehung dar?

Die Synchronisationsbeziehung zeigt den Durchsatz des Netzwerkadapters der Gruppe des Daten-Brokers. Wenn Sie die Synchronisierungsleistung durch die Verwendung mehrerer Datenmakler beschleunigen, ist der Durchsatz die Summe des gesamten Datenverkehrs. Dieser Durchsatz wird alle 20 Sekunden aktualisiert.



=== Ich habe Performance-Probleme. Können wir die Anzahl der gleichzeitigen Übertragungen begrenzen?

Wenn Sie sehr große Dateien haben (mehrere TIBS pro), kann es lange dauern, bis der Transfer-Prozess abgeschlossen ist, und die Leistung kann beeinträchtigt werden.

Eine Begrenzung der Anzahl gleichzeitiger Übertragungen kann hilfreich sein. link:task-get-help.html["Kontaktieren Sie uns für Hilfe"] .



=== Warum ist die Performance mit Azure NetApp Files niedrig?

Wenn Sie Daten mit oder von Azure NetApp Files synchronisieren, können Ausfälle und Performance-Probleme auftreten, sobald das Service-Level der Festplatte Standard ist.

Ändern Sie den Service-Level auf Premium oder Ultra, um die Synchronisationsperformance zu verbessern.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["Erfahren Sie mehr über Azure NetApp Files Service-Level und Durchsatz"^].



=== Wie viele Datenvermittler werden in einer Gruppe benötigt?

Wenn Sie eine neue Beziehung erstellen, beginnen Sie mit einem einzelnen Datenmanager in einer Gruppe (es sei denn, Sie haben einen vorhandenen Datenvermittler ausgewählt, der zu einer beschleunigten Synchronisierungsbeziehung gehört). In vielen Fällen kann ein einzelner Daten-Broker die Performance-Anforderungen für eine Synchronisierungsbeziehung erfüllen. Wenn dies nicht der Fall ist, können Sie die Sync-Performance beschleunigen, indem Sie der Gruppe zusätzliche Datenvermittler hinzufügen. Sie sollten jedoch zunächst andere Faktoren prüfen, die sich auf die Synchronisierungsleistung auswirken können.

Mehrere Faktoren können die Datenübertragungsleistung beeinflussen. Die Gesamt-Sync-Performance kann durch Netzwerkbandbreite, Latenz und Netzwerktopologie sowie die VM-Spezifikationen des Data Brokers und die Performance des Storage-Systems beeinträchtigt werden. Ein einzelner Daten-Broker kann beispielsweise in einer Gruppe 100 MB/s erreichen, während der Festplattendurchsatz auf dem Ziel möglicherweise nur 64 MB/s zulässt Folglich versucht die Gruppe des Daten-Brokers, die Daten zu kopieren, doch kann das Ziel die Performance der Gruppe des Daten-Brokers nicht erreichen.

Überprüfen Sie also die Performance Ihres Netzwerks und den Festplattendurchsatz auf dem Ziel.

Anschließend können Sie die Synchronisierung beschleunigen, indem Sie einer Gruppe weitere Datenvermittler hinzufügen, um die Last dieser Beziehung zu teilen. link:task-managing-relationships.html#accelerate-sync-performance["Erfahren Sie, wie Sie die synchrone Performance beschleunigen"].



== Dinge löschen

Die folgenden Fragen beziehen sich auf das Löschen von Synchronisierungsbeziehungen und -daten aus Quellen und Zielen.



=== Was geschieht, wenn ich meine BlueXP Kopier- und Synchronisierungsbeziehung lösche?

Durch das Löschen einer Beziehung werden alle zukünftigen Daten synchronisiert und die Zahlung wird beendet. Alle Daten, die mit dem Ziel synchronisiert wurden, bleiben unverändert.



=== Was passiert, wenn ich etwas von meinem Quellserver lösche? Wird sie auch aus dem Ziel entfernt?

Wenn Sie eine aktive Synchronisierungsbeziehung haben, wird das auf dem Quellserver gelöschte Element bei der nächsten Synchronisierung standardmäßig nicht vom Ziel gelöscht. Es gibt jedoch eine Option in den Synchronisierungseinstellungen für jede Beziehung, bei der Sie definieren können, dass die BlueXP Kopie und Synchronisierung Dateien am Zielspeicherort löschen, wenn sie aus der Quelle gelöscht wurden.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["Hier erfahren Sie, wie Sie die Einstellungen für eine Synchronisierungsbeziehung ändern"].



=== Was passiert, wenn ich etwas von meinem Ziel lösche? Wird es auch aus meiner Quelle entfernt?

Wenn ein Element aus dem Ziel gelöscht wird, wird es nicht aus der Quelle entfernt. Die Beziehung verläuft von der Quelle zum Ziel. Beim nächsten Synchronisierungszyklus vergleicht BlueXP Kopier- und Synchronisierungsvorgang die Quelle mit dem Ziel, identifiziert fehlende Elemente und BlueXP kopiert und synchronisiert sie erneut vom Quell- zum Zielsystem.



== Fehlerbehebung

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["NetApp Knowledgebase: BlueXP Kopier- und Synchronisierungs-FAQ: Support und Fehlerbehebung"^]



== Data Broker - tief greifend

Die folgende Frage bezieht sich auf den Data Broker.



=== Können Sie die Architektur des Data Brokers erläutern?

Sicher. Hier die wichtigsten Punkte:

* Der Data Broker ist eine Node.js-Anwendung, die auf einem Linux-Host ausgeführt wird.
* Mit BlueXP Copy and Sync wird der Daten-Broker wie folgt implementiert:
+
** AWS: Aus einer AWS CloudFormation Vorlage
** Azure: Von Azure Resource Manager
** Google: Von Google Cloud Deployment Manager
** Wenn Sie Ihren eigenen Linux-Host verwenden, müssen Sie die Software manuell installieren


* Die Data Broker-Software aktualisiert sich automatisch auf die neueste Version.
* Der Data Broker nutzt AWS SQS als zuverlässigen und sicheren Kommunikationskanal sowie zur Steuerung und Überwachung. SQS bietet auch eine Persistenzschicht.
* Sie können einer Gruppe weitere Datenvermittler hinzufügen, um die Übertragungsgeschwindigkeit zu erhöhen und die Hochverfügbarkeit zu erhöhen. Bei Ausfall eines Data Brokers besteht Service-Ausfallsicherheit.

