---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: Es gibt zwei Möglichkeiten, für Synchronisierungsbeziehungen zu bezahlen, nachdem die 14-tägige kostenlose Testversion abgelaufen ist. Die erste Option ist „Pay-as-you-go“. Die zweite Option besteht darin, Lizenzen direkt von NetApp zu erwerben. 
---
= Bezahlen für Synchronisierungsbeziehungen, sobald die kostenlose Testversion endet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Es gibt zwei Möglichkeiten, für Synchronisierungsbeziehungen zu bezahlen, nachdem die 14-tägige kostenlose Testversion abgelaufen ist. Die erste Option besteht darin, AWS oder Azure zu abonnieren, um nutzungsbasiert zu bezahlen oder jährlich zu zahlen. Die zweite Option besteht darin, Lizenzen direkt von NetApp zu erwerben.

Sie können den AWS Marketplace oder den Azure Marketplace abonnieren. Sie können sich nicht von beiden anmelden.

Sie haben die Möglichkeit, Lizenzen von NetApp mit einem Marketplace-Abonnement zu verwenden. Wenn Sie beispielsweise 25 Synchronisierungsbeziehungen haben, können Sie die ersten 20 Synchronisierungsbeziehungen mit einer Lizenz bezahlen und dann mit den restlichen 5 Synchronisierungsbeziehungen von AWS oder Azure bezahlen.

link:concept-licensing.html["Erfahren Sie mehr über die Funktionsweise von Lizenzen"].

Wenn Sie nicht sofort zahlen, nachdem Ihre kostenlose Testversion endet, werden Sie nicht in der Lage sein, zusätzliche Beziehungen zu erstellen. Bestehende Beziehungen werden nicht gelöscht, Sie können jedoch erst dann Änderungen an ihnen vornehmen, wenn Sie eine Lizenz abonnieren oder eingeben.

Die Lizenzen sollten über die BlueXP Kopier- und Synchronisierungsfunktion oder die entsprechende Website und *nicht* über ein digitales Wallet gemanagt werden.



== [[aws]]abonnieren von AWS

AWS ermöglicht Ihnen, nutzungsbasiert zu zahlen oder jährlich zu zahlen.

.Schritte zum nutzungsbasierten Bezahlen
. Klicken Sie Auf *Sync > Licensing*.
. Wählen Sie *AWS* aus
. Klicken Sie auf *Abonnieren* und dann auf *Weiter*.
. Abonnieren Sie den AWS Marketplace, und melden Sie sich anschließend wieder beim BlueXP Kopier- und Synchronisierungsservice an, um die Registrierung abzuschließen.
+
Das folgende Video zeigt den Prozess:

+
video::video_cloud_sync_registering.mp4[width=848,height=480]


.Jährliche Zahlung
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Rufen Sie die AWS Marketplace Seite auf"^].
. Klicken Sie auf *Weiter zur Anmeldung*.
. Wählen Sie Ihre Vertragsoptionen aus und klicken Sie auf *Vertrag erstellen*.




== [[Azure]]abonnieren von Azure

Azure ermöglicht Ihnen, nutzungsbasiert zu zahlen oder jährlich zu zahlen.

.Was Sie benötigen
Ein Azure Benutzerkonto, das Mitarbeiter- oder Eigentümerberechtigungen für das entsprechende Abonnement besitzt.

.Schritte
. Klicken Sie Auf *Sync > Licensing*.
. Wählen Sie *Azure*.
. Klicken Sie auf *Abonnieren* und dann auf *Weiter*.
. Klicken Sie im Azure-Portal auf *Erstellen*, wählen Sie Ihre Optionen aus und klicken Sie auf *Abonnieren*.
+
Wählen Sie * monatlich*, um auf Stundenbasis zu bezahlen, oder *jährlich*, um für ein Jahr im Voraus zu bezahlen.

. Wenn die Bereitstellung abgeschlossen ist, klicken Sie im Benachrichtigungs-Popup auf den Namen der SaaS-Ressource.
. Klicken Sie auf *Configure Account*, um zur BlueXP Kopier- und Synchronisierungsfunktion zurückzukehren.
+
Das folgende Video zeigt den Prozess:

+
video::video_cloud_sync_registering_azure.mp4[width=848,height=480]




== [[Lizenzen]]Erwerb von Lizenzen von NetApp und Hinzufügen zu BlueXP Kopier- und Synchronisierungsfunktion

Damit Sie vorab für Ihre Synchronisierungsbeziehungen bezahlen, müssen Sie eine oder mehrere Lizenzen erwerben und sie dem BlueXP Kopier- und Synchronisierungsservice hinzufügen.

.Was Sie benötigen
Sie benötigen die Seriennummer Ihrer Lizenz und den Benutzernamen und das Kennwort für das NetApp Support Site Konto, mit dem die Lizenz verknüpft ist.

.Schritte
. Erwerben Sie eine Lizenz per mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Kauf%20Anforderung[Kontakt mit NetApp].
. Klicken Sie in BlueXP auf *Sync > Licensing*.
. Klicken Sie auf *Lizenz hinzufügen* und fügen Sie die erforderlichen Informationen hinzu:
+
.. Geben Sie die Seriennummer ein.
.. Wählen Sie das NetApp Support Site Konto aus, das mit der Lizenz verknüpft ist, die Sie hinzufügen:
+
*** Wenn Ihr Konto bereits zu BlueXP hinzugefügt wurde, wählen Sie es aus der Dropdown-Liste aus.
*** Wenn Ihr Konto noch nicht hinzugefügt wurde, klicken Sie auf *NSS-Anmeldeinformationen hinzufügen*, geben Sie den Benutzernamen und das Passwort ein, klicken Sie auf *Registrieren* und wählen Sie es aus der Dropdown-Liste aus.


.. Klicken Sie Auf *Hinzufügen*.






== Aktualisieren einer Lizenz

Wenn Sie eine von NetApp erworbene BlueXP Kopier- und Synchronisierungslizenz verlängern, wird das neue Ablaufdatum in der BlueXP Kopier- und Synchronisierungslizenz nicht automatisch aktualisiert. Sie müssen die Lizenz erneut hinzufügen, um das Ablaufdatum zu aktualisieren. Die Lizenzen sollten über die BlueXP Kopier- und Synchronisierungsfunktion oder die entsprechende Website und *nicht* über ein digitales Wallet gemanagt werden.

.Schritte
. Klicken Sie in BlueXP auf *Sync > Licensing*.
. Klicken Sie auf *Lizenz hinzufügen* und fügen Sie die erforderlichen Informationen hinzu:
+
.. Geben Sie die Seriennummer ein.
.. Wählen Sie das NetApp Support Site Konto aus, das mit der Lizenz verknüpft ist, die Sie hinzufügen.
.. Klicken Sie Auf *Hinzufügen*.




.Ergebnis
Durch das Kopieren und Synchronisieren von BlueXP wird die vorhandene Lizenz mit dem neuen Ablaufdatum aktualisiert.
